### ISSUE TITLE
Support expressing multiple "element parametrisations" in the input YAML file

### ISSUE THREAD

**Issue by aplowman** [hpcflow/hpcflow-new#324]
Since we are [refactoring](https://github.com/hpcflow/hpcflow-new/issues/311) `Workflow.add_task` to use `WorkflowTask.add_elements`, and we want to be able to [write out the template YAML file](https://github.com/hpcflow/hpcflow-new/issues/323) in any workflow state, we need a way to represent the association of multiple element parametrisations in the task YAML.

The existing format is like this:

```yaml
tasks:
  - schemas: [demo_task_1]
    inputs:
      p2: 201
      p5: 501
    sequences:
      - path: inputs.p1
        nesting_order: 0
        values: [101, 102]
```

The new format will be like this:

```yaml
tasks:
  - schemas: [demo_task_1]
    elements:
      - inputs:
          p2: 201
          p5: 501
        sequences:
          - path: inputs.p1
            nesting_order: 0
            values: [101, 102]
```

The existing format should still be supported, and should be "cast" to the new format when parsed.
