### ISSUE TITLE
`NullScheduler.options` should be passed as a dict instead of a list

### ISSUE THREAD

**Issue by aplowman** [hpcflow/hpcflow-new#609]
Currently, a list is expected. E.g. in a YAML template:

```yaml
resources:
  any:
    scheduler_args:
      options:
        - "-p PARTITION_NAME"
        - "--time=00:30:00"
```

However, we want to be able to _merge_ options from defaults supplied in the config file. E.g.:

```yaml
schedulers:
  direct:
    defaults: {}
  slurm:
    defaults:
      options: ["-A ACCOUNT_NAME"]
```

With the resulting jobscript containing these lines:

```
#SBATCH -A ACCOUNT_NAME
#SBATCH -p PARTITION_NAME
#SBATCH --time=00:30:00
```

So, options should be specified like this instead:

```yaml
resources:
  any:
    scheduler_args:
      options:
        --partition: PARTITION_NAME
        --time: 00:30:00
        --requeue: null
```

where the `requeue` flag has been included to demonstrate that flags can be passed with a `null`/`None` mapping value.

Where multiple values for a given option might exist, we should accept the mapping value being a list, like this (e.g. in SGE):

```yaml
resources:
  any:
    scheduler_args:
      options:
        -l: [RESOURCE_1=value_1, RESOURCE_2=value_2]
```

which would result in two option lines in the jobscript:

```
#$ -l RESOURCE_1=value_1
#$ -l RESOURCE_2=value_2
```
