### ISSUE TITLE
Support the concept of inheritance within environments

### ISSUE THREAD

**Issue by aplowman** [hpcflow/hpcflow-new#711]
In the MatFlow subset simulation workflows, we have DAMASK tasks running adjacent to Python scripts that implement the Markov Chain Monte Carlo (MCMC) algorithm. DAMASK actions use the `damask_parse_env` environment, and the MCMC scripts use a plain old `python_env`. When resolving jobscripts with `resources.combine_scripts: True`, these two types of actions are segregated into separate jobscripts---due to the different environment names---when in principle they could be combined, because `damask_parse_env` also has a Python interpreter with numpy etc available.

To fix this, we could provide hpcflow with information about environment inheritance. In this case, we could declare that the `damask_parse_env` environment is a _type of_ `python_env` environment. If the jobscript's environment is set to `damask_parse_env`, hpcflow can then assume that any adjacent actions that use the `python_env` environment can also be allocated to that same jobscript.

We would need a way to overide this behaviour. For example, by prefixing the environment name with an exclamation mark: 

```yaml
task_schemas:
  - objective: generate_next_state
    inputs: ...
    outputs: ...
    actions:
      - script: <<script:uq/generate_next_state_ACS.py>>
        script_data_in: direct
        script_data_out: direct
        script_exe: python_script
        environments:
          - scope:
              type: any
            environment: !python_env # indicates this exact environment must be used, and not any "child" environment
```

(Note that in the case of `resources.combine_scripts: False` this wouldn't be an issue, because multiple environments can be used within the same jobscript.)

**Comment by aplowman** [comment]
An alternative to this might be to support matching multiple environments, and hpcflow will choose whichever is available, or if all are available whichever results in the fewest jobscripts:

```yaml
task_schemas:
  - objective: generate_next_state
    inputs: ...
    outputs: ...
    actions:
      - script: <<script:uq/generate_next_state_ACS.py>>
        script_data_in: direct
        script_data_out: direct
        script_exe: python_script
        environments:
          - scope:
              type: any
            environment: python_env | damask_parse_env
```
