### ISSUE TITLE
Ability to generate inputs from statistical distributions

### ISSUE THREAD

**Issue by aplowman** [hpcflow/hpcflow-new#717]
It would be nice if we could generate single input values from distributions without resorting to creating a single-value sequence. E.g.: 

```yaml
tasks:
  - schema: my_schema        
    sequences: # this works
      - path: inputs.p2
        values::from_random_uniform:
          low: 0.0
          high: 1.0
          num: 1
    inputs: # this doesn't work
      p1::from_random_uniform:
        low: 0.0
        high: 1.0
```
