### ISSUE TITLE
SLURM partition not detected from config

### ISSUE THREAD

**Issue by gcapes** [hpcflow/hpcflow-new#801]
Trying to run this simple workflow on CSF3 using slurm, 
```
template_components:
  task_schemas:
  - objective: locate_matlab
    actions:
    - commands:
      - command: which matlab
      environments:
      - scope:
          type: any
        environment: matlab_env  

tasks:
- schema: locate_matlab

resources:
  any:
    scheduler_args:
      options:
        --time: 00:30:00
```
I came up against this error:
```
sbatch: error: Batch job submission failed: Invalid partition name specified
Traceback (most recent call last):
  File "/net/scratch/mbexegc2/matflow-demo-workflows/.venv/bin/matflow", line 8, in <module>
    sys.exit(cli())
  File "/net/scratch/mbexegc2/matflow-demo-workflows/.venv/lib64/python3.9/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/net/scratch/mbexegc2/matflow-demo-workflows/.venv/lib64/python3.9/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/net/scratch/mbexegc2/matflow-demo-workflows/.venv/lib64/python3.9/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/net/scratch/mbexegc2/matflow-demo-workflows/.venv/lib64/python3.9/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/net/scratch/mbexegc2/matflow-demo-workflows/.venv/lib64/python3.9/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/net/scratch/mbexegc2/matflow-demo-workflows/.venv/lib64/python3.9/site-packages/hpcflow/sdk/cli.py", line 253, in make_and_submit_workflow
    out = app.make_and_submit_workflow(
  File "/net/scratch/mbexegc2/matflow-demo-workflows/.venv/lib64/python3.9/site-packages/hpcflow/sdk/app.py", line 1644, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "/net/scratch/mbexegc2/matflow-demo-workflows/.venv/lib64/python3.9/site-packages/hpcflow/sdk/app.py", line 2897, in _make_and_submit_workflow
    submitted_js = wk.submit(
  File "/net/scratch/mbexegc2/matflow-demo-workflows/.venv/lib64/python3.9/site-packages/hpcflow/sdk/core/workflow.py", line 3336, in submit
    raise WorkflowSubmissionFailure(exceptions)
hpcflow.sdk.core.errors.WorkflowSubmissionFailure: 
Some jobscripts in submission index 0 could not be submitted:
Jobscript 0 at path: '/net/scratch/mbexegc2/matflow-demo-workflows/wheresmatlab_2025-04-17_103905/artifacts/submissions/0/jobscripts/js_0.sh'
Submit command: ['sbatch', '--parsable', '/net/scratch/mbexegc2/matflow-demo-workflows/wheresmatlab_2025-04-17_103905/artifacts/submissions/0/jobscripts/js_0.sh'].
Reason: 'Non-empty stderr from submit command.'
Submission stderr:
  sbatch: error: Batch job submission failed: Invalid partition name specified
```

This was side-stepped by specifying the partition in the jobscript as shown below:
```
template_components:
  task_schemas:
  - objective: locate_matlab
    actions:
    - commands:
      - command: which matlab
      environments:
      - scope:
          type: any
        environment: matlab_env  

tasks:
- schema: locate_matlab

resources:
  any:
    scheduler_args:
      options:
        --time: 00:30:00
        --partition: serial
```

**Comment by gcapes** [comment]
This is my config

<pre>╭────────────────────────────────────────────────────────────────────────────────────────────────────── Config &apos;manchester-CSF3-slurm&apos; ──────────────────────────────────────────────────────────────────────────────────────────────────────╮
│  machine               <font color="#4E9A06">&apos;manchester-CSF3-new&apos;</font>                                                                                                                                                                                               │
│  log_file_path         <font color="#75507B"><b>PosixPath</b></font><b>(</b><font color="#4E9A06">&apos;/mnt/iusers01/support/mbexegc2/.matflow-new/logs/MatFlow_v0.3.0a155.log&apos;</font><b>)</b>                                                                                                                                │
│  task_schema_sources   <b>[]</b>                                                                                                                                                                                                                  │
│  parameter_sources     <b>[]</b>                                                                                                                                                                                                                  │
│  command_file_sources  <b>[]</b>                                                                                                                                                                                                                  │
│  environment_sources   <b>[</b><font color="#75507B"><b>PosixPath</b></font><b>(</b><font color="#4E9A06">&apos;/mnt/iusers01/support/mbexegc2/.matflow-new/envs-slurm.yaml&apos;</font><b>)]</b>                                                                                                                                          │
│  default_scheduler     <font color="#4E9A06">&apos;slurm&apos;</font>                                                                                                                                                                                                             │
│  default_shell         <font color="#4E9A06">&apos;bash&apos;</font>                                                                                                                                                                                                              │
│  schedulers            <b>{</b>                                                                                                                                                                                                                   │
│                            <font color="#4E9A06">&apos;direct&apos;</font>: <b>{</b><font color="#4E9A06">&apos;defaults&apos;</font>: <b>{}}</b>,                                                                                                                                                                                     │
│                            <font color="#4E9A06">&apos;slurm&apos;</font>: <b>{</b>                                                                                                                                                                                                      │
│                                <font color="#4E9A06">&apos;defaults&apos;</font>: <b>{</b><font color="#4E9A06">&apos;shebang_args&apos;</font>: <font color="#4E9A06">&apos;--login&apos;</font><b>}</b>,                                                                                                                                                                    │
│                                <font color="#4E9A06">&apos;partitions&apos;</font>: <b>{</b>                                                                                                                                                                                             │
│                                    <font color="#4E9A06">&apos;serial&apos;</font>: <b>{</b><font color="#4E9A06">&apos;num_cores&apos;</font>: <b>[</b><font color="#06989A"><b>1</b></font>, <font color="#06989A"><b>1</b></font>, <font color="#06989A"><b>1</b></font><b>]}</b>,                                                                                                                                                                     │
│                                    <font color="#4E9A06">&apos;multicore&apos;</font>: <b>{</b>                                                                                                                                                                                          │
│                                        <font color="#4E9A06">&apos;num_nodes&apos;</font>: <b>[</b><font color="#06989A"><b>1</b></font>, <font color="#06989A"><b>1</b></font>, <font color="#06989A"><b>1</b></font><b>]</b>,                                                                                                                                                                             │
│                                        <font color="#4E9A06">&apos;num_cores&apos;</font>: <b>[</b><font color="#06989A"><b>2</b></font>, <font color="#06989A"><b>1</b></font>, <font color="#06989A"><b>168</b></font><b>]</b>,                                                                                                                                                                           │
│                                        <font color="#4E9A06">&apos;num_cores_per_node&apos;</font>: <b>[</b><font color="#06989A"><b>2</b></font>, <font color="#06989A"><b>1</b></font>, <font color="#06989A"><b>168</b></font><b>]</b>,                                                                                                                                                                  │
│                                        <font color="#4E9A06">&apos;parallel_modes&apos;</font>: <b>[</b><font color="#4E9A06">&apos;distributed&apos;</font>, <font color="#4E9A06">&apos;shared&apos;</font>, <font color="#4E9A06">&apos;hybrid&apos;</font><b>]</b>                                                                                                                                               │
│                                    <b>}</b>,                                                                                                                                                                                                      │
│                                    <font color="#4E9A06">&apos;multinode&apos;</font>: <b>{</b><font color="#4E9A06">&apos;num_nodes&apos;</font>: <b>[</b><font color="#06989A"><b>2</b></font>, <font color="#06989A"><b>1</b></font>, <font color="#75507B"><i>None</i></font><b>]</b>, <font color="#4E9A06">&apos;num_cores&apos;</font>: <b>[</b><font color="#06989A"><b>80</b></font>, <font color="#06989A"><b>40</b></font>, <font color="#75507B"><i>None</i></font><b>]</b>, <font color="#4E9A06">&apos;num_cores_per_node&apos;</font>: <b>[</b><font color="#06989A"><b>40</b></font>, <font color="#06989A"><b>40</b></font>, <font color="#06989A"><b>40</b></font><b>]</b>, <font color="#4E9A06">&apos;parallel_modes&apos;</font>: <b>[</b><font color="#4E9A06">&apos;distributed&apos;</font>, <font color="#4E9A06">&apos;hybrid&apos;</font><b>]}</b>                                                  │
│                                <b>}</b>                                                                                                                                                                                                           │
│                            <b>}</b>                                                                                                                                                                                                               │
│                        <b>}</b>                                                                                                                                                                                                                   │
│  shells                <b>{</b><font color="#4E9A06">&apos;bash&apos;</font>: <b>{</b><font color="#4E9A06">&apos;defaults&apos;</font>: <b>{}}}</b>                                                                                                                                                                                          │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
</pre>

**Comment by gcapes** [comment]
Adam is aware of this bug, and we have a workaround for now.

**Comment by dkfellows** [comment]
Hmm, it's _supposed_ to pick the first compatible partition... except it's probably saying "I don't know how many cores are wanted for this job, so that partition can't be matched against as that has a range of cores set".

I'm guessing that saying that the job in question only needs one core will make it work. If so, that's a superior workaround (as it's a portable fix) and we can then fix things by adjusting the resource request to say that the number of cores wanted is 1 if not already known (when doing this match-by-approximation algorithm in `SlurmPosix.process_resources`).

**Comment by dkfellows** [comment]
Linked PR says "If we're choosing partitions by matching resources, and the user hasn't actually stated what resources they want, assume they just want a single core." It's a bit of a janky hack of a fix, but it will at least mean that small jobs will run (assuming there's a "serial" partition in the first place). User controls which they get in part by the order of partition descriptions.

**Comment by gcapes** [comment]
I don't think that's the (only) issue here.  I get the same error from this workflow (last two lines modified compared with above):
```yaml
template_components:
  task_schemas:
  - objective: locate_matlab
    actions:
    - commands:
      - command: which matlab
      environments:
      - scope:
          type: any
        environment: matlab_env  

tasks:
- schema: locate_matlab

resources:
  any:
    scheduler_args:
      directives:
        --time: 00:30:00
#        --partition: serial
    num_cores: 1
```

**Comment by gcapes** [comment]
@dkfellows

**Comment by dkfellows** [comment]
Whoops; attention was elsewhere.

Adapted workflow to this test case:
```yml
template_components:
  task_schemas:
  - objective: locate_bash
    outputs:
      - parameter: bash_location
    actions:
    - commands:
      - command: which bash
        stdout: <<parameter:bash_location>>
      environments:
      - scope:
          type: any
        environment: null_env

tasks:
- schema: locate_bash

resources:
  any:
    scheduler_args:
      directives:
        --time: 00:30:00
#        --partition: serial
    num_cores: 1
```
```python
@pytest.mark.slurm
def test_workflow_2(tmp_path: Path, null_config):
    hf.config.add_scheduler("slurm")
    wk = make_test_data_YAML_workflow("workflow_2_slurm.yaml", path=tmp_path)
    wk.submit(wait=True, add_to_known=False)
    bash_location = wk.tasks[0].elements[0].outputs.bash_location
    assert isinstance(bash_location, hf.ElementParameter)
    assert "bash" in bash_location.value
```
