### ISSUE TITLE
Use parameter validation data to set a base input value where appropriate?

### ISSUE THREAD

**Issue by aplowman** [hpcflow/hpcflow-new#812]
If a parameter has some type validation data associated with it in the `parameters.yaml` template components file, we could use this to avoid the user having to specify the "base" parameter, where they are using a sequence to parametrise a sub-part of that parameter. For example:

```yaml
tasks:
  - schema: s1
    sequences:
      - path: inputs.p1.a
        values: [1, 2, 3]
    inputs:
      p1: {}     # <-- currently required to prevent compaints about missing input source for p1
```
Basically, we would need to know the container type from the parameter validation data, so that the user doesn't need to specify the base parameter (`p1` in this case).

(Thanks to @mikedwhite for the idea!)
