### ISSUE TITLE
Misleading exception when trying to submit a workflow with no runs

### ISSUE THREAD

**Issue by aplowman** [hpcflow/hpcflow-new#822]
This workflow has no actions:

```yaml
yml = """
name: test
template_components:
  task_schemas:
    - objective: t1
      inputs:
        - parameter: p1
tasks:
  - schema: t1
    inputs:
      p1: 1
"""
wk = hf.Workflow.from_YAML_string(YAML_str=yml)
wk.submit()
```
But when we submit it we get a `ZeroDivisionError` when using the (default) `zarr` store. When we use the `json` store we get no exception, but an odd "Submitted 0 jobscripts" message. In both cases, I think we should get a message about the submission having no runs to execute, like we raise here: https://github.com/hpcflow/hpcflow-new/blob/e3eae5f35845b11d3d27b64dc60932959929d25f/hpcflow/sdk/core/workflow.py#L3195.
